# Generated by Django 3.1.1 on 2020-09-25 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PrivateGlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_email_address', models.EmailField(blank=True, help_text="l'adresse à utiliser pour tous les courriers électroniques sortants", max_length=254, null=True, verbose_name="e-mail de l'expéditeur")),
            ],
            options={'verbose_name': 'Private Global Settings', 'verbose_name_plural': 'Private Global Settings'},
        ),
        migrations.CreateModel(
            name='PublicGlobalSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={'verbose_name': 'Public Global Settings', 'verbose_name_plural': 'Private Global Settings'},
        ),
    ]
